version: '3'
services:
  stm32compiler:
    image: 139.9.186.120:8080/cortex-m_compiler:latest
    container_name: stm32_compiler
    restart: unless-stopped
    command: /bin/bash
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./workdir:/root/workdir
